### PR TITLE
Fix #316 - OutOfMemoryError when fetching data from large tables

### LINKED ISSUE #316: OutOfMemoryError when fetching data from large tables
Doobie: v0.3.0, 0.2.4
Scala: 2.11.7
System: Mac OS El Capitan
DB: PostgreSQL v9.4.4

Considering a table with 10M records, processing of q1 and q2 behaves differently:
```
val q1 = sql"SELECT * FROM tbl LIMIT 1000".query[Blah]
val q2 = sql"SELECT * FROM tbl LIMIT 10000000".query[Blah]

q1.process.take(5).quick.run // r1
q2.process.take(5).quick.run // r2
```

`r1` usually works fine, while `r2` fails with OutOfMemory (it's trying to fetch the whole 10M records beforehand).

### PR DESCRIPTION
**Pull request by guersam**
(NOTE: It's based upon #318)

This PR fixes two issues:
- `doobie.hi.resultset.getNextChunk` ignores given chunk size
- [The entire ResultSet is loaded at once](https://jdbc.postgresql.org/documentation/94/query.html#query-with-cursor)

### CODE REVIEW

File: yax/core/src/main/scala/doobie/hi/resultset.scala [hunk 1]
```diff
@@ -206,7 +206,7 @@ object resultset {
       val b = Vector.newBuilder[A]
       while (n > 0 && rs.next) {
```
Comment (guersam) [inline yax/core/src/main/scala/doobie/hi/resultset.scala]: BTW, it'll yield empty vector when a chunkSize <= 0 is given. Should it be prevented at all or be handled as a special case?

**Comment by tpolecat** [comment]
Thanks for figuring this out, I wasn't seeing it.

File: yax/core/src/main/scala/doobie/hi/resultset.scala (hunk 1 above)
Comment (tpolecat) [inline yax/core/src/main/scala/doobie/hi/resultset.scala]: This is by design. I guess we could throw an exception since it doesn't really make any sense but it doesn't bother me as-is.

**Comment by tpolecat** [comment]
Huh I thought merging #318 would remove those commits from this PR. I guess not.

File: yax/core/src/main/scala/doobie/hi/resultset.scala [hunk 2]
```diff
@@ -206,7 +206,7 @@ object resultset {
...
         b += A.unsafeGet(rs, 1)
-        n += 1
+        n -= 1
```
Comment (tpolecat) [inline yax/core/src/main/scala/doobie/hi/resultset.scala]: hurr

**Comment by tpolecat** [comment]
Works. This is great.

File: yax/core/src/main/scala/doobie/hi/resultset.scala (hunk 1 above)
Comment (guersam) [inline yax/core/src/main/scala/doobie/hi/resultset.scala]: `(P)S.setFetchSize(0)` disables cursor so that the driver fetches all results at once. There might be some users who want this behavior, but I'm okay to be opinionated here.

Comment (tpolecat) [inline yax/core/src/main/scala/doobie/hi/resultset.scala]: If you're doing that there's not much reason to be using a stream, but yeah we should review the doc. Opened #322 for followup.
